# Dockerfile.maven3.9.9-eclipse-temurin17-node20
FROM maven:3.9.9-eclipse-temurin-17

# Install Node.js
ENV NODE_VERSION=20
RUN apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - && \
    apt-get install -y nodejs

# Install Yarn
RUN npm install -g yarn


# Verify installations
RUN java -version && mvn -version && node -v && npm -v && yarn -v

CMD ["/bin/bash"]
